"""
    Tagesschau API

    Die Tagesschau ist eine Nachrichtensendung der ARD (Abkürzung für Arbeitsgemeinschaft der öffentlich-rechtlichen Rundfunkanstalten der Bundesrepublik Deutschland), die von ARD-aktuell in Hamburg produziert und mehrmals täglich ausgestrahlt wird. ARD-aktuell ist seit 1977 die zentrale Fernsehnachrichtenredaktion der ARD, bei welcher es sich wiederum um einen Rundfunkverbund handelt, der aus den Landesrundfunkanstalten und der Deutschen Welle besteht.<br>Über die hier dokumentierte API stehen auf [www.tagesschau.de](https://www.tagesschau.de) aktuelle Nachrichten und Medienbeiträge im JSON-Format zur Verfügung.<br>  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.tagesschau.api.default_api import DefaultApi  # noqa: E501

from deutschland import tagesschau


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api2(self):
        """Test case for api2

        Wichtige Nachrichten und Eilmeldungen  # noqa: E501
        """
        pass

    def test_channels(self):
        """Test case for channels

        Aktuelle Kanäle  # noqa: E501
        """
        pass

    def test_homepage(self):
        """Test case for homepage

        Ausgewählte aktuelle Nachrichten und Eilmeldungen  # noqa: E501
        """
        pass

    def test_multimedia(self):
        """Test case for multimedia

        Multimedia  # noqa: E501
        """
        pass

    def test_news(self):
        """Test case for news

        Aktuelle Nachrichten und Eilmeldungen  # noqa: E501
        """
        pass

    def test_newsfeed(self):
        """Test case for newsfeed

        Newsfeed  # noqa: E501
        """
        pass

    def test_ressort(self):
        """Test case for ressort

        Ressort-spezifische Nachrichten  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        Suche  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
